language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
    - vendor/bin/tester tests -s -c tests/php-unix.ini
    - php code-checker/src/code-checker.php -d src

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
    - composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source

    # Create databases.ini
    - cp ./tests/Database/databases.sample.ini ./tests/Database/databases.ini

    # Create Postgre database
    - psql -c 'CREATE DATABASE nette_test' -U postgres

git:
    depth: 10
