<?php

/**
 * Test: Nette\Database\Connection: reflection
 * @dataProvider? databases.ini  mysql
 */

declare(strict_types=1);

use Tester\Assert;

require __DIR__ . '/connect.inc.php'; // create $connection

Nette\Database\Helpers::loadFromFile($connection, __DIR__ . '/files/mysql-nette_test3.sql');


$version80 = version_compare($connection->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION), '8.0', '>=');
$reflection = $connection->getReflection();
$columns = $reflection->getTable('types')->columns;

$expectedColumns = [
	'unsigned_int' => [
		'name' => 'unsigned_int',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 11,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'int' => [
		'name' => 'int',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 11,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'smallint' => [
		'name' => 'smallint',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 6,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'tinyint' => [
		'name' => 'tinyint',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 4,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'mediumint' => [
		'name' => 'mediumint',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 9,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'bigint' => [
		'name' => 'bigint',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 20,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'bool' => [
		'name' => 'bool',
		'table' => 'types',
		'type' => 'bool',
		'size' => 1,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'bit' => [
		'name' => 'bit',
		'table' => 'types',
		'type' => 'string',
		'size' => 1,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'decimal' => [
		'name' => 'decimal',
		'table' => 'types',
		'type' => 'int',
		'size' => 10,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'decimal2' => [
		'name' => 'decimal2',
		'table' => 'types',
		'type' => 'decimal',
		'size' => 10,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'float' => [
		'name' => 'float',
		'table' => 'types',
		'type' => 'float',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'double' => [
		'name' => 'double',
		'table' => 'types',
		'type' => 'float',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'date' => [
		'name' => 'date',
		'table' => 'types',
		'type' => 'date',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'time' => [
		'name' => 'time',
		'table' => 'types',
		'type' => 'timeint',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'datetime' => [
		'name' => 'datetime',
		'table' => 'types',
		'type' => 'datetime',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'timestamp' => [
		'name' => 'timestamp',
		'table' => 'types',
		'type' => 'datetime',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'year' => [
		'name' => 'year',
		'table' => 'types',
		'type' => 'int',
		'size' => $version80 ? null : 4,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'char' => [
		'name' => 'char',
		'table' => 'types',
		'type' => 'string',
		'size' => 1,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'varchar' => [
		'name' => 'varchar',
		'table' => 'types',
		'type' => 'string',
		'size' => 30,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'binary' => [
		'name' => 'binary',
		'table' => 'types',
		'type' => 'bin',
		'size' => 1,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'varbinary' => [
		'name' => 'varbinary',
		'table' => 'types',
		'type' => 'bin',
		'size' => 30,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'blob' => [
		'name' => 'blob',
		'table' => 'types',
		'type' => 'bin',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'tinyblob' => [
		'name' => 'tinyblob',
		'table' => 'types',
		'type' => 'bin',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'mediumblob' => [
		'name' => 'mediumblob',
		'table' => 'types',
		'type' => 'bin',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'longblob' => [
		'name' => 'longblob',
		'table' => 'types',
		'type' => 'bin',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'text' => [
		'name' => 'text',
		'table' => 'types',
		'type' => 'string',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'tinytext' => [
		'name' => 'tinytext',
		'table' => 'types',
		'type' => 'string',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'mediumtext' => [
		'name' => 'mediumtext',
		'table' => 'types',
		'type' => 'string',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'longtext' => [
		'name' => 'longtext',
		'table' => 'types',
		'type' => 'string',
		'size' => null,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'enum' => [
		'name' => 'enum',
		'table' => 'types',
		'type' => 'string',
		'size' => 0,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
	'set' => [
		'name' => 'set',
		'table' => 'types',
		'type' => 'string',
		'size' => 0,
		'nullable' => true,
		'default' => null,
		'autoIncrement' => false,
		'primary' => false,
	],
];

Assert::same(
	$expectedColumns,
	array_map(fn($c) => [
		'name' => $c->name,
		'table' => $c->table->name,
		'type' => $c->type,
		'size' => $c->size,
		'nullable' => $c->nullable,
		'default' => $c->default,
		'autoIncrement' => $c->autoIncrement,
		'primary' => $c->primary,
	], $columns),
);
