name: Static Analysis (only informative)

on:
    push:
        branches:
          - master

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none

            - run: composer install --no-progress --prefer-dist
            - run: composer phpstan -- --no-progress
              continue-on-error: true # is only informative
